# Meant to be sourced by 'magic-enviro'
# Adds project's bin dir to path

# Checks for project's bin directory to be in path
bindir_load() {
	if ! [[ -d ${PROJECT_DIR}/bin ]]; then
		echo -e "\t${C_YELLOW}WARNING:${C_NC} ${C_BOLD}bin/ directory requested, but not found.${C_NC}"
		mkdir ${PROJECT_DIR}/bin
		echo -e "\t${C_GREEN}INFO:${C_NC} ${C_BOLD}'${PROJECT_DIR}/bin'${C_NC} ${C_GREEN}created${C_NC}."
	fi
	# Adds ${PROJECT_DIR}/bin if not already there
	if ! [[ "$PATH" =~ (^|:)"${PROJECT_DIR}/bin"(:|$) ]]; then
		PATH="${PROJECT_DIR}/bin":$PATH
		echo -e "\t${C_GREEN}INFO:${C_NC} ${C_BOLD}'${PROJECT_DIR}/bin'${C_NC} added to local path."
	fi
}


bindir_unload() {
# Passes current $PATH to an array
	OLD_IFS=$IFS && IFS=:
	tmp_path=($PATH) && unset IFS
# array operation to delete project's bin entry from path
	tmp_path=(${tmp_path[@]%%*${PROJECT_DIR}/bin*})
	IFS=:
# sets the new path
	PATH=`echo "${tmp_path[*]}"` && IFS=$OLD_IFS
	
	unset tmp_path
	unset OLD_IFS
}
